# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BarChartCustomize' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   pod 'Charts'

  # Pods for BarChartCustomize

  target 'BarChartCustomizeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BarChartCustomizeUITests' do
    # Pods for testing
  end

end
